name: hero_dex
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_typeahead: ^5.0.0
  http: ^1.0.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/heroes.json
